POC: Global - MVC
iNewLegend/shop-catalog pull request #34
Opened 2021-05-15 14:30 UTC by iNewLegend

2021-06-18 06:53 UTC, iNewLegend commented on frontend/core/model/array-class.js
> +		const getHash = () => objectHash( this?._parent?.getModelData ? this._parent.getModelData() : null ),
Dont use `getHash`

2021-09-15 07:00 UTC, StyleShit requested changes

2021-09-15 09:09 UTC, iNewLegend commented on frontend/components/cart/component.js
> +		}
Hey thanks for the review, those events will be removed ASAP, and moved to new `$core.commands`.

2021-09-15 10:39 UTC, iNewLegend commented on frontend/components/cart/component.js
> +		}
handled.

2021-09-16 06:19 UTC, merged